// <auto-generated />
using System;
using EfPerformance.Code;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfPerformance.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20220319214732_Job_Properties")]
    partial class Job_Properties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EfPerformance.Code.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prop0")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop25")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop26")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop27")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop28")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop29")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop30")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop31")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop32")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop33")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop34")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop35")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop36")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop37")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop38")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop39")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop40")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop41")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop42")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop43")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop44")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop45")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop46")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop47")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop48")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop49")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop50")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop51")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop52")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop53")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop54")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop55")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop56")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop57")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop58")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop59")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop60")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop61")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop62")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop63")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop64")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop65")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop66")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop67")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop68")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop69")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop70")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop71")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop72")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop73")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop74")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop75")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop76")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop77")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop78")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop79")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prop9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
