using System;

namespace EfPerformance.Code;

public class Job
{
    public Guid Id { get; set; }
    public DateTime LastUpdatedAt { get; set; }

    public string Prop0 { get; set; }
    public string Prop1 { get; set; }
    public string Prop2 { get; set; }
    public string Prop3 { get; set; }
    public string Prop4 { get; set; }
    public string Prop5 { get; set; }
    public string Prop6 { get; set; }
    public string Prop7 { get; set; }
    public string Prop8 { get; set; }
    public string Prop9 { get; set; }
    public string Prop10 { get; set; }
    public string Prop11 { get; set; }
    public string Prop12 { get; set; }
    public string Prop13 { get; set; }
    public string Prop14 { get; set; }
    public string Prop15 { get; set; }
    public string Prop16 { get; set; }
    public string Prop17 { get; set; }
    public string Prop18 { get; set; }
    public string Prop19 { get; set; }
    public string Prop20 { get; set; }
    public string Prop21 { get; set; }
    public string Prop22 { get; set; }
    public string Prop23 { get; set; }
    public string Prop24 { get; set; }
    public string Prop25 { get; set; }
    public string Prop26 { get; set; }
    public string Prop27 { get; set; }
    public string Prop28 { get; set; }
    public string Prop29 { get; set; }
    public string Prop30 { get; set; }
    public string Prop31 { get; set; }
    public string Prop32 { get; set; }
    public string Prop33 { get; set; }
    public string Prop34 { get; set; }
    public string Prop35 { get; set; }
    public string Prop36 { get; set; }
    public string Prop37 { get; set; }
    public string Prop38 { get; set; }
    public string Prop39 { get; set; }
    public string Prop40 { get; set; }
    public string Prop41 { get; set; }
    public string Prop42 { get; set; }
    public string Prop43 { get; set; }
    public string Prop44 { get; set; }
    public string Prop45 { get; set; }
    public string Prop46 { get; set; }
    public string Prop47 { get; set; }
    public string Prop48 { get; set; }
    public string Prop49 { get; set; }
    public string Prop50 { get; set; }
    public string Prop51 { get; set; }
    public string Prop52 { get; set; }
    public string Prop53 { get; set; }
    public string Prop54 { get; set; }
    public string Prop55 { get; set; }
    public string Prop56 { get; set; }
    public string Prop57 { get; set; }
    public string Prop58 { get; set; }
    public string Prop59 { get; set; }
    public string Prop60 { get; set; }
    public string Prop61 { get; set; }
    public string Prop62 { get; set; }
    public string Prop63 { get; set; }
    public string Prop64 { get; set; }
    public string Prop65 { get; set; }
    public string Prop66 { get; set; }
    public string Prop67 { get; set; }
    public string Prop68 { get; set; }
    public string Prop69 { get; set; }
    public string Prop70 { get; set; }
    public string Prop71 { get; set; }
    public string Prop72 { get; set; }
    public string Prop73 { get; set; }
    public string Prop74 { get; set; }
    public string Prop75 { get; set; }
    public string Prop76 { get; set; }
    public string Prop77 { get; set; }
    public string Prop78 { get; set; }
    public string Prop79 { get; set; }
}